title: Network Web Manga Download Site
description: A Favourite Chinese Network All Manga
show_excerpts: true
google_analytics:
cayman:
  date_format: "%b %-d, %Y"
theme: jekyll-theme-cayman
show_downloads: true
#false
#cayman-blog:
#  date_format: "%b %-d, %Y"
#theme: jekyll-theme-cayman-blog
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://favouritechinesenetworkallmangadownload.github.io" # change this to the base hostname & protocol for your site
#target-blank:
#    rel: nofollow
social_links:
  - rss: rss
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
#header_pages:
#  - Favourite
#  - MangaSites
#header_page_refs: ['favourite', 'mangasites', 'contact']
#
#
#
#
#
#
#
#
