title: Network Web Manga Download Site
description: A Favourite Chinese Network All Manga
#show_downloads: false
#google_analytics:
cayman:
  date_format: "%b %-d, %Y"
theme: jekyll-theme-cayman
encoding: UTF-8
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://favouritechinesenetworkallmangadownload.github.io" # change this to the base hostname & protocol for your site
#target-blank:
#    rel: nofollow
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-category-pages
categories: [Category Pages Plugin, jekyll]
permalink: /:year/:month/:day/:title:output_ext
disqus:
  shortname: networkwebmangadownload
#
#
#
#
#
#
#
#
#
#  deaults:  # _posts
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single #post
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true
#
#header_page_refs: ['favourite'], ['mangasites'], ['contact']
#
#
