title: Network Web Manga Download Site
description: A Favourite Chinese Network All Manga
show_downloads: false
google_analytics:
#cayman:
#  date_format: "%b %-d, %Y"
#theme: jekyll-theme-cayman
rtd:
  date_format: "%b %-d, %Y"
theme: jekyll-rtd-theme
#cayman-blog:
#  date_format: "%b %-d, %Y"
#  permalink: /:categories/:year/:month/:day/:title:output_ext
#theme: jekyll-theme-cayman-blog
#baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
#url: "https://favouritechinesenetworkallmangadownload.github.io" # change this to the base hostname & protocol for your site
plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
plugins:  
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
copyright: false
edit: false
logo: false # relative path to your image, eg: assets/logo.png
disqus: false # your disqus username
addons: false
addons_branch: false # means addons branch
rougify: github
