title: Web Manga Download Site
description: A Web Manga Download Site
baseurl: "/MangaSite" # the subpath of your site, e.g. /blog
url: "favouritechinesenetworkallmangadownload.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#github_username:  mohamedosama914
#gitlab_username:  pages
#theme: jekyll-theme-minimal
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
#Mint skin: mint
locale: "en"
title_separator: "default Web | Manga Download Site"
subtitle: "Version 2.0"
name: "Manga Download"
header:
  teaser: /assets/images/my-awesome-post-teaser.jpg
  logo: "/assets/images/88x88.png"
masthead_title: "My Custom Download Site"
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
permalink: /:categories/:title/
breadcrumbs: true  # disabled by default
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true      
words_per_minute: 250
.post__meta-sep::before {
  content: "\2022";
  padding-left: 0.5em;
  padding-right: 0.5em;
}
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

#repository: "username/repo-name"
#repository: # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
#comments:
#  provider: "utterances"
#  utterances:
#    theme: "github-light" # "github-dark"
#    issue_term: "pathname"
reCaptcha:
  enabled: true
#  siteKey: # ""
#  secret: # ""
atom_feed:
  path: "http://feeds.feedburner.com/youFeedname"
plugins:
  - jekyll-feed
  
  
  
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#exclude:
#    - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
