title: Web Manga Download Site
description: A Web Manga Download Site
baseurl: "/MangaSite" # the subpath of your site, e.g. /blog
url: "favouritechinesenetworkallmangadownload.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#github_username:  mohamedosama914
#gitlab_username:  pages
#theme: jekyll-theme-minimal
#plugins:
#  - jekyll-feed
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
#Mint skin: mint
locale: "en"
title_separator: "default Web | Manga Download Site"
subtitle: "Version 2.0"
name: "Manga Download"
header:
  teaser: /assets/images/my-awesome-post-teaser.jpg
  logo: "/assets/images/88x88.png"
masthead_title: "My Custom Download Site"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#exclude:
#    - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
