title: Web Manga Download Site
description: A Web Manga Download Site
baseurl: "/MangaSite/" # the subpath of your site, e.g. /blog
url: "https://favouritechinesenetworkallmangadownload.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#github_username:  mohamedosama914
#gitlab_username:  pages
theme: jekyll-theme-minimal
#plugins:
#  - jekyll-feed
  
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
    - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
