title: Web Manga Download Site
description: A Favourite Chinese Network All Manga
show_downloads: true
#google_analytics:
cayman-blog:
  date_format: "%b %-d, %Y"
theme: jekyll-theme-cayman  
author: "Nicolas Morange"
#image: /thumbnail-jumbo.png
#username: lorepirri
#  site:
#  admins:
#
#
