theme: jekyll-theme-cayman
minimal_mistakes_skin: "neon" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
name: "Manga Download"
title: Web Manga Download Site
title_separator: "Web Manga Download Site"
defaults:  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
timezone: America/New_York
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
permalink: /:categories/:title/    
