title: Network Web Manga Download Site
description: A Favourite Chinese Network All Manga
show_downloads: false
google_analytics:
#cayman:
#  date_format: "%b %-d, %Y"
#theme: jekyll-theme-cayman
cayman-blog:
  date_format: "%b %-d, %Y"
theme: jekyll-theme-cayman-blog
#theme: alpha_jekyll_theme
plugins:
  - jemoji
  - jekyll-target-blank
gems: ["jemoji"]
target-blank:
    rel: nofollow
header_page_refs: ['now', 'about', 'contact']
#
#
#
#
