title: Network Web Manga Download Site
description: A Favourite Chinese Network All Manga
#show_downloads: false
#google_analytics:
cayman:
  date_format: "%b %-d, %Y"
#theme: jekyll-theme-cayman
#encoding: UTF-8
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://favouritechinesenetworkallmangadownload.github.io" # change this to the base hostname & protocol for your site
#target-blank:
#    rel: nofollow
#social_links:
#  - rss: rss
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
#header_page_refs: ['favourite'], ['mangasites'], ['contact']
rss: #/feed.xml
#
#
#
#
#
#
#
#
search:
 provider: default # "default" (default), false, "google", "custom"
 google:
   custom_search_engine_id: # Google Custom Search Engine ID
#author:
#  type      : # "person" (default), "organization"
#  name      : Your Name
#  url       :
#  avatar    : # path or url of avatar image (square)
#  bio       :  path.
#  email     :
#favicon :
#  enabled : true
#  local :
#    enabled : true
#    partial_url : /img/.png
#    type : png
#  remote :
#    enabled : false
#    full_url : false
#    type : false
#navbar :
#  archive :
#    enabled : false
  categories :
    enabled : true
  tags :
    enabled : true
#  social_links :
#    enabled : false
#  external_links :
#    enabled : false
#external_links :
#  header : Links
#  links :
#    - link :
#      name : Baking Kookys
#      url : http://bakingkookys.com
disqus :
 enabled : true
 shortname : thedereck
 show_comment_count : true
#rss :
#  enabled : true
#  managingeditor :
#    enabled : true
#    managingeditor : @.com ()
#  webmaster :
#    enabled : true
#    webmaster : @.com ()
#  ttl :
#    enabled : true
#    ttl : 300
#  image :
#    enabled : true
#    image : https://www.gravatar.com/avatar/2f8947394b8acb62ed0f08df91055f27.png?s=200
#alert : true
#notice : true
