title: Network Web Manga Download Site
description: A Favourite Chinese Network All Manga
show_downloads: false
google_analytics:
cayman:
  date_format: "%b %-d, %Y"
theme: jekyll-theme-cayman
#cayman-blog:
#  date_format: "%b %-d, %Y"
#theme: jekyll-theme-cayman-blog
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://favouritechinesenetworkallmangadownload.github.io" # change this to the base hostname & protocol for your site
gems:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag  
#target-blank:
#    rel: nofollow
github_username: nohamedosama914
rss: rss
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - Favourite
  - MangaSites
show_excerpts: false
#header_page_refs: ['favourite', 'mangasites', 'contact']
#
#
#
#
#
#
#
#
